//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "person")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub person_id: i32,
    pub person_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rx_info::Entity")]
    RxInfo,
}

impl Related<super::rx_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RxInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
