// Copyright 2022-2023, Ryan Pavlik <ryan@ryanpavlik.com>
// SPDX-License-Identifier: GPL3+

//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reminder_policy")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub reminder_id: i32,
    pub rx_id: i32,
    pub starting_date: Option<String>,
    pub include_rx_duration: bool,
    pub offset: i32,
    pub allow_saturday: bool,
    pub allow_sunday: bool,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rx_info::Entity",
        from = "Column::RxId",
        to = "super::rx_info::Column::RxId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RxInfo,
}

impl Related<super::rx_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RxInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
