//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rx_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub rx_id: i32,
    pub person_id: i32,
    pub rx_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fill_request::Entity")]
    FillRequest,
    #[sea_orm(
        belongs_to = "super::person::Entity",
        from = "Column::PersonId",
        to = "super::person::Column::PersonId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Person,
}

impl Related<super::fill_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FillRequest.def()
    }
}

impl Related<super::person::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Person.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
